In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr[2:6]

array([3, 4, 5, 6])

In [6]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [4,5,6,7,8]

arr1 = np.array([lst1, lst2, lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [12]:
arr1[1:4,1:3]

array([[3, 4],
       [5, 6]])